# Generated by Django 5.1.3 on 2025-07-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EVChargingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=250)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
